using System.ComponentModel.DataAnnotations;

namespace LeatherShopAPI.Models;

public enum MessageDirection
{
    Incoming,  // Customer → Business
    Outgoing   // Business → Customer (bot or admin)
}

public class ChatMessage
{
    [Key]
    public int Id { get; set; }

    public int CustomerId { get; set; }
    public Customer Customer { get; set; } = null!;

    public MessageDirection Direction { get; set; }

    /// <summary>Message type: text, interactive, image, etc.</summary>
    [MaxLength(30)]
    public string MessageType { get; set; } = "text";

    /// <summary>Full message content / body text</summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>Who sent it: customer name, "Bot", or "Admin"</summary>
    [MaxLength(200)]
    public string SenderName { get; set; } = string.Empty;

    /// <summary>True if the outgoing message was generated by the chatbot (not admin)</summary>
    public bool IsFromBot { get; set; }

    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
}
