// <auto-generated />
using System;
using LeatherShopAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeatherShopAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221094400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeatherShopAPI.Models.BroadcastMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SentCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRecipients")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BroadcastMessages");
                });

            modelBuilder.Entity("LeatherShopAPI.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CustomerId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("LeatherShopAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LeatherShopAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LeatherShopAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("LeatherShopAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("Category");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Royal Leather",
                            Category = "Wallet",
                            CreatedAt = new DateTime(2026, 2, 21, 9, 43, 58, 186, DateTimeKind.Utc).AddTicks(3744),
                            Description = "Premium genuine leather wallet with multiple card slots",
                            ImageUrl = "/images/wallet1.jpg",
                            IsActive = true,
                            Name = "Classic Leather Wallet",
                            Price = 899m,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2026, 2, 21, 9, 43, 58, 186, DateTimeKind.Utc).AddTicks(3746)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Royal Leather",
                            Category = "Belt",
                            CreatedAt = new DateTime(2026, 2, 21, 9, 43, 58, 186, DateTimeKind.Utc).AddTicks(3751),
                            Description = "Formal leather belt with silver buckle",
                            ImageUrl = "/images/belt1.jpg",
                            IsActive = true,
                            Name = "Executive Leather Belt",
                            Price = 1299m,
                            StockQuantity = 30,
                            UpdatedAt = new DateTime(2026, 2, 21, 9, 43, 58, 186, DateTimeKind.Utc).AddTicks(3752)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Heritage Craft",
                            Category = "Bag",
                            CreatedAt = new DateTime(2026, 2, 21, 9, 43, 58, 186, DateTimeKind.Utc).AddTicks(3753),
                            Description = "Handcrafted messenger bag for daily use",
                            ImageUrl = "/images/bag1.jpg",
                            IsActive = true,
                            Name = "Leather Messenger Bag",
                            Price = 3499m,
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2026, 2, 21, 9, 43, 58, 186, DateTimeKind.Utc).AddTicks(3753)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "StepCraft",
                            Category = "Shoes",
                            CreatedAt = new DateTime(2026, 2, 21, 9, 43, 58, 186, DateTimeKind.Utc).AddTicks(3755),
                            Description = "Premium leather formal shoes",
                            ImageUrl = "/images/shoes1.jpg",
                            IsActive = true,
                            Name = "Leather Oxford Shoes",
                            Price = 4999m,
                            StockQuantity = 15,
                            UpdatedAt = new DateTime(2026, 2, 21, 9, 43, 58, 186, DateTimeKind.Utc).AddTicks(3755)
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Royal Leather",
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 2, 21, 9, 43, 58, 186, DateTimeKind.Utc).AddTicks(3756),
                            Description = "Stylish leather keychain with metal ring",
                            ImageUrl = "/images/keychain1.jpg",
                            IsActive = true,
                            Name = "Leather Keychain",
                            Price = 299m,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2026, 2, 21, 9, 43, 58, 186, DateTimeKind.Utc).AddTicks(3756)
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Heritage Craft",
                            Category = "Bag",
                            CreatedAt = new DateTime(2026, 2, 21, 9, 43, 58, 186, DateTimeKind.Utc).AddTicks(3758),
                            Description = "Slim leather sleeve for 15-inch laptops",
                            ImageUrl = "/images/sleeve1.jpg",
                            IsActive = true,
                            Name = "Leather Laptop Sleeve",
                            Price = 2499m,
                            StockQuantity = 25,
                            UpdatedAt = new DateTime(2026, 2, 21, 9, 43, 58, 186, DateTimeKind.Utc).AddTicks(3758)
                        });
                });

            modelBuilder.Entity("LeatherShopAPI.Models.CartItem", b =>
                {
                    b.HasOne("LeatherShopAPI.Models.Customer", "Customer")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeatherShopAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LeatherShopAPI.Models.Order", b =>
                {
                    b.HasOne("LeatherShopAPI.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LeatherShopAPI.Models.OrderItem", b =>
                {
                    b.HasOne("LeatherShopAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeatherShopAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LeatherShopAPI.Models.Customer", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LeatherShopAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
